name: Test evok.
on: [push, pull_request]
jobs:
  test_evok_deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: Install software required for the test.
        run: |
          sudo apt-get install qemu-system-arm libguestfs-tools
      - name: Run test
        run: |
          bash ${{ github.workspace }}/misc/test.sh
      - run: echo "This job's status is ${{ job.status }}."

